name=input("enter your name :")
print(f"my name is :{name}")
print(type(name))
age=int(input("enter age:"))
print("age:",age)
print(type(age))
Qualification=input("your qualification:")
print(f"Qualification:")
print(type(Qualification))
cgpa=float(input("final year cgpa:"))
print("cgpa:",cgpa)
print(type(cgpa))
Phone_no=int(input("enter Phone_no:"))
print("Phone no:",Phone_no)
print(type(Phone_no))